package com.beecow.ui;

public class CreateBeeCowPageUI {
	public static String SELLER_LBL = "//span[@class='plus-txt']";
	public static String CONTENTUP_LBL= "//span[@class='icon-upload02']";
	public static String POST_BTN = "//button[@beetranslate='beecow.item.action.post']//span";
	public static String SELECTIMAGE_MSG = "//label[@beetranslate='beecow.store.item.image.error.chooseImage']//span";
	public static String EMPTYNAME_MSG ="//label[@beetranslate='beecow.store.item.image.error.productName']//span";
	public static String EMPTYCATEGORY_MSG ="//label[@beetranslate='beecow.item.error.category']//span";
	public static String EMPTYDESCRIPTION_MSG ="//label[@beetranslate='beecow.item.error.description']//span";
	public static String EMPTYNUMBER_MSG ="//label[@beetranslate='beecow.item.error.itemQty']//span";
	public static String EMPTYPRICE_MSG ="//label[@beetranslate='beecow.item.error.price']//span";
	public static String EMPTYWEIGHT_MSG ="//label[@beetranslate='beecow.item.error.shipping.range']//span";
	public static String EMPTYWIDTH_MSG ="//label[@beetranslate='beecow.item.error.shipping.width.require']//span";
	public static String EMPTYLENGTH_MSG ="//label[@beetranslate='beecow.item.error.shipping.length.require']//span";
	public static String EMPTYHIGH_MSG ="//label[@beetranslate='beecow.item.error.shipping.height.require']//span";
	public static String POPUP = "//div[@class='gosell_popup']";
	public static String CLOSEPOPUP_BTN = "//button[@aria-label='Close']//span";
	public static String UPLOADIMAGE = "//div[@id='upload-empty']//input";
	public static String PRODUCTNAME_TXT= "//input[@name='name']";
	public static String DESCRIPTION_TXT ="//div[@class='fr-element fr-view']//p";
	public static String QUANLITY_TXT ="//input[@id='org-qty']";
	public static String PRICE_TXT="//input[@id='original-price']";
	public static String WEIGHT_TXT="//input[@formcontrolname='weight']";
	public static String WIDTH_TXT="//input[@formcontrolname='width']";
	public static String LENGTH_TXT="//input[@formcontrolname='length']";
	public static String HIGHT_TXT="//input[@formcontrolname='height']";
	public static String DROPDOWN_CATEGORY01 ="//div[contains(@class,'category-left')]//button";
	public static String DROPDOWN_CATEGORY02 ="//div[contains(@class,'category-mid')]//button";
	public static String DROPDOWN_CATEGORY03 ="//div[contains(@class,'category-right')]//button";
	public static String LISTCATEGORY01_LBL = "//div[contains(@class,'category-left')]/button/following-sibling::ul/li";
	public static String LISTCATEGORY02_LBL = "//div[contains(@class,'category-mid')]/button/following-sibling::ul/li";
	public static String LISTCATEGORY03_LBL = "//div[contains(@class,'category-right')]/button/following-sibling::ul/li";
	public static String EXPECTEDINVALIDWEIGHT_MSG = "//label[@beetranslate='beecow.item.error.shipping.range']/span";
	public static String EXPECTEDINVALIDWIDTH_MSG = "//label[@beetranslate='beecow.item.error.shipping.width.range']/span";
	public static String EXPECTEDINVALIDLENGHT_MSG = "//label[@beetranslate='beecow.item.error.shipping.length.range']/span";
	public static String EXPECTEDINVALIDHEIGHT_MSG = "//label[@beetranslate='beecow.item.error.shipping.height.range']/span";
	public static String SUBMITSUCCESS_LBL ="//p[@beetranslate='beecow.item.modal.postSuccess']//span";
	public static String VIEWLISTPRODUCT_BTN ="//button[@beetranslate='beecow.item.modal.viewList']//span";
	public static String SKU_TXT ="//input[@id='org-sku']";
	public static String EDIT_BTN ="//a[contains(@href,'%s')]//a";
	public static String DELETE_BTN = "//button[@beetranslate='beecow.common.delete' and contains(@class,'btn-line-grey')]//span";
	public static String CONFIRMDELETE_BTN = "//button[@beetranslate='beecow.common.delete' and contains(@class,'btn-line-pink')]//span";
	public static String EXPECTEDNAMEPRODUCT = "//a[contains(@href,'%s')]//p[@class='pro-name']";
	public static String EXPECTEDPRICE = "//a[contains(@href,'%s')]//p[@class='price-disc']";
	public static String EDITPEN_ICON= "//span[@class='icon-pen-underline']";
	public static String EDITEDSUBMIT_BTN = "//button[@beetranslate='beecow.item.action.update']";
	public static String VIEWAFTEREDIT_BTN ="//button[@beetranslate='beecow.item.modal.viewProduct']//span";
	public static String EDIT02_BTN= "//button[@id='edit-product']//span";
}
